#############################################################################################################################################################
# {S3 bucket}             
# More info about Function Resource: 
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html                        
#############################################################################################################################################################
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    - An Amazon CloudFront distribution to expose the application
    - An Amazon S3 bucket for hosting bucket and cloudfront access logs

Parameters:
  StackName:
    Type: String
  DomsStaticWebPageBucketArn:
    Type: String    
  DomsStaticWebPageBucketName:
    Type: String    
  DomsStaticWebPageBucketRegionalDomainName:
    Type: String    
  DomsStaticWebPageLoggingBucketArn:
    Type: String    
  DomsStaticWebPageLoggingBucketName:
    Type: String    
  DomsStaticWebPageLoggingBucketRegionalDomainName:
    Type: String    


Resources:

  # <<<<<<< The Amazon CloudFront distribution exposing our Single Page Application >>>>>>>>>
  CFDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !Ref DomsStaticWebPageBucketRegionalDomainName
          Id: Doms-ui-S3Origin
          S3OriginConfig:
            OriginAccessIdentity: ""
          OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
        Enabled: 'true'
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          - OPTIONS
          TargetOriginId: Doms-ui-S3Origin
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf # CORS-S3Origin
          ResponseHeadersPolicyId: 67f7725c-6f97-4210-82d7-5512b31e9d03 # SecurityHeadersPolicy
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_All
        Logging:
          Bucket: !Ref DomsStaticWebPageLoggingBucketRegionalDomainName
          Prefix: 'doms-ui-access-logs'
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
          MinimumProtocolVersion: 'TLSv1.2_2021'

  # <<<<<<< The Amazon CloudFront origin access control >>>>>>>>>
  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties: 
      OriginAccessControlConfig:
        Description: Default Origin Access Control
        Name: !Ref AWS::StackName
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

#############################################################################################################################################################
# {output}
# More info about Output:
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html
#############################################################################################################################################################
Outputs:
  CFDistributionArn:
    Value: !GetAtt CFDistribution.Arn
    Export:
      Name: CFDistributionArn
  CFDistributionName:
    Value: !Ref CFDistribution
    Export:
      Name: CFDistributionName
  CFDistributionId:
    Value: !GetAtt CFDistribution.DomainName
    Export:
      Name: CFDistributionId
