#############################################################################################################################################################
# {S3 bucket}             
# More info about Function Resource: 
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html                        
#############################################################################################################################################################
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  An Amazon S3 bucket for hosting the application:

Parameters:
  StackName:
    Type: String

Resources:
  
  # <<<<<<< The Amazon S3 bucket into which our Single Page Application build files must be deployed>>>>>>>>>
  DomsStaticWebPageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ "-", [!Ref StackName, !Ref AWS::AccountId, "StaticWebPage"]]
      PublicAccessBlockConfiguration:
        BlockPublicAcls : true
        BlockPublicPolicy : true
        IgnorePublicAcls : true
        RestrictPublicBuckets : true

  
#############################################################################################################################################################
# {output}
# More info about Output:
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html
#############################################################################################################################################################
Outputs:
  DomsStaticWebPageBucketArn:
    Value: !GetAtt DomsStaticWebPageBucket.Arn
    Export:
      Name: DomsStaticWebPageBucketArn
  DomsStaticWebPageBucketName:
    Value: !Ref DomsStaticWebPageBucket
    Export:
      Name: DomsStaticWebPageBucketName

