#############################################################################################################################################################
# {S3 bucket}             
# More info about Function Resource: 
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html                        
#############################################################################################################################################################
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  An Amazon S3 bucket for hosting the application:

Parameters:
  StackName:
    Type: String
  DomsStaticWebPageBucketArn:
    Type: String
  DomsStaticWebPageBucketName:
    Type: String
  CFDistributionName:
    Type: String
Resources:

  # <<<<<<< The Amazon S3 bucket into which our Single Page Application build files must be deployed >>>>>>>>>
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref DomsStaticWebPageBucketName
      PolicyDocument:
        Id: Doms-cloudfront-s3-Policy
        Version: 2012-10-17
        Statement:
          - Sid: PolicyForCloudFrontPrivateContent
            Effect: Allow
            Resource: !Sub ${DomsStaticWebPageBucketArn}/*
            Principal:
              Service: cloudfront.amazonaws.com
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${CFDistributionName}
            Action: 's3:GetObject*'
