#############################################################################################################################################################
# {AWS SAM template}
# More info about Function Resource:
# https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
#############################################################################################################################################################
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Creates the infrastructure to host and expose a Single Page Application:
      - An Amazon S3 bucket for hosting the application
      - An Amazon CloudFront distribution to expose the application
      - An Amazon S3 bucket for hosting bucket and cloudfront access logs

#$$$$ https://github.com/aws-samples/react-cors-spa/blob/main/react-cors-spa-stack.yaml

Parameters:
  StackName:
    Type: String
    Default: "shavika-doms-frontend"
  ParameterInstancePrefix:
    Type: String
    Default: "shavika-doms-frontend"
  TagProvisioner:
    Type: String
    Default: "SAM"
  TagProject:
    Type: String
    Default: "DOMS"
  TagBusinessUnit:
    Type: String
    Default: "Platform"
  TagBusinessModel:
    Type: String
    Default: "shared"
  TagProductVersion:
    Type: String
    Default: "1.0.0"

Resources:

  # ********************** S3 Stack ****************** #
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stack-s3.yaml
      Parameters:
        StackName: !Ref StackName
      Tags:
        - Key: Name
          Value: S3Stack

