name: "Terraform doe Infracost Analysis"

on:
  workflow_call:
    inputs:
      env:
        required: false
        type: string
        default: 'dev'
      working-directory:
        required: false
        type: string
        default: 'terraform'
      terraform-var-file:
        required: false
        type: string
        default: ''
      usage-file:
        required: false
        type: string
        default: './.env/dev/infracost-usage.yml'
      infracost-flag:
        required: false
        type: boolean
        default: true

jobs:
  inftacost:
    name: Infracost Analysis
    runs-on: ubuntu-latest
    env:
      TF_ROOT: ${{inputs.working.directory}}
    environment: ${{inputs.env || 'dev'}}

    if: inputs.infracost-flag
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Checkout
        uses: actions/checkout@v3     

      - name: Print debug info
        run: |
          echo environment is ${{ input.env }}
          echo TF_ROOT is ${TF_ROOT}
          echo terraform-var-file is ${{ inputs.terraform-var-file }}

      # Generate Infracost json file
      - name: Generate Infracost estimate
        run: |
          # passes a NPM_TOKEN which has access to private repo as client app doesn't pass such credential in when calling tf composite module.
          # credit: https://github.com/hashicorp/setup-terraform/issues/33
          git config --global url."https://oauth2:${{ secret.NPM_TOKEN }}@github.com".insteadOf https://github.com
          export INFRACOST_API_KEY=${{ secrets.INFRACOST_API_KEY }}
          cd ${TF_ROOT}
          infracost breakdown --path=. \
                              --terraform-var-file=${{ inputs.terraform-var-file }} \
                              --usage-file ${{ inputs.usage-file }} \
                              --format=json \
                              --out-file=/temp/infracost.json

      # Post a comment to the PR using the 'update' behavior.
      # This creates a single comment and updates it. The "quietest" option.
      # The other valid behaviors are:
      # delete-and-new: Delete previous comment and create a new one.
      # hide-and-new: Minimize previous comment and create a new one.
      # new: new cost estimate comment on every push.
      # update: Update a cost estimate comment when there is a changes in the cost estimate.
      # Also refer the https://www.infracost.io/docs/features/cli_commands/#comment-on-pull-requests 
      - name: Post Infracost comment
        run: |
          export INFRACOST_API_KEY=${{ secrets.INFRACOST_API_KEY }}
          inftacost comment github --path=/temp/infracost.json \
                                   --repo=$GITHUB_REPOSITORY \
                                   --github-token=${{github.token}} \
                                   --commit=$GITHUB_SHA \
                                   --behavior=new \
                                   --policy-path=${TF_ROOT}/infracost-policy.rego                   

