name: Terraform frontend provision

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the workflow'
        type: environment
        required: true

permissions:
  contents: read

jobs:

  infracost:
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/actions/terraform-infracost.yml@main
    with:
      env: ${{ github.event.inputs.environment }}
      working-directory: ./terraform/frontend
      terraform-var-file: ./.env/${{ github.event.inputs.environment || 'dev' }}/terraform.tfvars
      usage-file: ./.env/${{ github.event.inputs.environment || 'dev' }}/infracost-usage.yml
      infracost-flag: true
    secrets: inherit

  terraform:
    needs: infracost
    permissions:
      id-token: write
      contents: read
    uses: ./.github/actions/terraform.yml@main
    with:
      working-directory: ./terraform/frontend
      apply-branch: main
    secrets: inherit

